### ISSUE TITLE
License Discussion

### ISSUE THREAD

**Issue by missarah96** [UBC-MDS/fxtracker#76]

**Comment by markusnam** [comment]
Should have created on the `R` side.
Refer to https://github.com/UBC-MDS/fxtrackerR/issues/36

**Comment by THF-d8** [comment]
First of all, I think it is a good idea to use the same license for Python and R, since they pretty much serve the same functions. 
In my opinion, I would prefer to go with the MIT license for the following reasons:
1. It is simple and straightforward. Considering that our package is relatively small, we are probably better off choosing something simpler. 
2. It gives us the freedom to do whatever we want with our package with few restrictions 
3. It has a wide compatibility

**Comment by markusnam** [comment]
Yes, I also started a similar discussion on the `R` side. Let's discuss here and write our conclusion there later.

Same view as Crystal on using the same licence for `py` and `R`.

Also agree to use MIT licence. It is popular, widely used, and suits our simple packages for this project. Other options like GNU Licences would be too complicated for us.

**Comment by lennonay** [comment]
Yes, I agree with both of you. As we are not trying to make profit from fxtracker and fxtrackerR, the MIT license is an ideal choice for us.

**Comment by missarah96** [comment]
I also agree with you all. The MIT license is the perfect license for our package because it gives us right to obtain a copy of online software and associated files the right to use, copy, modify, merge, among other things, as long as the terms of the MIT license is mentioned in our work. It also gives others the right to copy and further develop our code which we are open to.

**Comment by markusnam** [comment]
Cool. We all agree to use MIT license for both `py` and `R`.
